### ISSUE TITLE
Marker file is not generated

### ISSUE THREAD

**Issue by YasuChiba** [colcon/colcon-ros-gradle#10]
Hi,
Thank you for maintaining ros2java!
 
In my understanding, current build tools related to the ros2java project don't generate the marker file described in [this document.](https://github.com/ament/ament_cmake/blob/master/ament_cmake_core/doc/resource_index.md)

Even if AMENT_PREFIX_PATH is provided by colcon-ros-gradle (#7), we need to create a marker file as well because the ros2 command cannot find the package without the marker file.
There seems to be a discussion about which project should implement this feature in ros2-java/ament_java#9
But I still not get which project should implement this.
So, as a temporary thing, I've implemented it in this project. 
https://github.com/YasuChiba/colcon-ros-gradle/commit/e299e2599481fdfece2d4d4da7f7457d1b95b914

I'll send out a PR. Can anyone check it out?

(I'm new to gradle/ament/colcon. I'm sorry if my understanding is wrong)

**Comment by jacobperron** [comment]
Yes, we are missing logic to install a marker file. I think we also should install the package.xml too. IMO, the gradle projects themselves should be responsible for this, perhaps through a plugin like [ament_gradle_plugin](https://github.com/ros2-java/ament_gradle_plugin) or some helper library, but I don't think it hurts if colcon-ros-gradle does this too.

Even better, would be if colcon could detect if the marker and package.xml were not being installed by the gradle project and emit a warning. This is what we do for ament_python packages, [for example](https://github.com/colcon/colcon-ros/blob/07c7e0622cd9eb4749a2ae1031da95fb405cb20c/colcon_ros/task/ament_python/build.py).

**Comment by jacobperron** [comment]
Resolved by #11
