### ISSUE TITLE
Release to PyPi

### ISSUE THREAD

**Issue by jacobperron** [colcon/colcon-ros-gradle#8]
Like other colcon packages, it would be convenient to have a release of `colcon-ros-gradle` (and `colcon-gradle`) on https://pypi.org/. Then I can stop installing from source :)

@esteve Let me know if you'd like me to help with this.

**Comment by esteve** [comment]
@jacobperron sorry, I miss this one. I'll release  `colcon-ros-gradle` tomorrow hopefully.

**Comment by jacobperron** [comment]
I've tagged and released 0.1.0: https://pypi.org/project/colcon-ros-gradle/0.1.0/
